<?php
/**
 * 🌟 Baganix Authentication API
 * Endpoint: api.Baganix.online/v1/auth.php
 * Handles Registration and Login.
 */

require_once '../config/database.php';
header('Content-Type: application/json');

// Get raw JSON payload from frontend
$data = json_decode(file_get_contents("php://input"));
$action = $_GET['action'] ?? '';

if ($action === 'register') {
    if (!isset($data->username) || !isset($data->email) || !isset($data->password)) {
        echo json_encode(["status" => "error", "message" => "Missing required fields."]);
        exit;
    }

    $username = $data->username;
    $email = $data->email;
    $password_hash = password_hash($data->password, PASSWORD_BCRYPT);
    $public_key = $data->public_key ?? null; // E2EE Public Key generated by JS

    // Use Prepared Statements ONLY (Rule 81)
    $stmt = $db->prepare("INSERT INTO users (username, email, password_hash, public_key) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("ssss", $username, $email, $password_hash, $public_key);

    try {
        $stmt->execute();
        echo json_encode([
            "status" => "success", 
            "message" => "Welcome to Baganix!", 
            "user_id" => $stmt->insert_id
        ]);
    } catch (Exception $e) {
        echo json_encode(["status" => "error", "message" => "Username or email already exists."]);
    }
    $stmt->close();

} elseif ($action === 'login') {
    if (!isset($data->email) || !isset($data->password)) {
        echo json_encode(["status" => "error", "message" => "Missing credentials."]);
        exit;
    }

    $email = $data->email;
    $stmt = $db->prepare("SELECT id, username, password_hash, aura_colors FROM users WHERE email = ?");
    $stmt->bind_param("s", $email);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($user = $result->fetch_assoc()) {
        if (password_verify($data->password, $user['password_hash'])) {
            // In a full production app, you would generate a JWT here.
            // For pure PHP simplicity right now, we return a mock token.
            $token = base64_encode(json_encode(["user_id" => $user['id'], "exp" => time() + 3600]));
            
            echo json_encode([
                "status" => "success",
                "token" => $token,
                "user" => [
                    "id" => $user['id'],
                    "username" => $user['username'],
                    "aura_colors" => $user['aura_colors']
                ]
            ]);
        } else {
            echo json_encode(["status" => "error", "message" => "Invalid password."]);
        }
    } else {
        echo json_encode(["status" => "error", "message" => "User not found."]);
    }
    $stmt->close();
} else {
    echo json_encode(["status" => "error", "message" => "Invalid action. Use ?action=register or ?action=login"]);
}
?>